## Docker-setup to quickly spawn a setup to run tests and develop against
version: "3.7"

services:
    redis:
        image: "redis:alpine"
        ports:
            - 6379:6379

    backend:
        image: "ghcr.io/impfen/services-inoeg:main"
        depends_on:
            - redis
        environment:
            - KIEBITZ_SETTINGS=/settings
        volumes:
            - "./testing/fixtures/keys:/settings"
        ports:
            - 11111:11111
            - 22222:22222
        command: "./kiebitz --level debug run all"
